### ISSUE TITLE
create a sample polling repository proxy server

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-repository-file-sample#3]
This is to create a sample polling repository proxy server for use in an eco system that does not issue federated queries, this server will contain 2 connectors:
- a repository connector that will point to a folder on the file system that contains csv files.
- an event mapper connector that will periodically issue queries to the repository connector, then will construct an OMRS event that will contain all of the entities and relationships.      

As this is a sample it will only return the first 10 files with a csv type it finds in the folder.

**Comment by davidradl** [comment]
> I have been thinking it over and I am wondering if this piece of work belongs in this repository. All of the other content is themed around Coco Pharmaceuticals - this is a very specific connector for a very specific situation with no reference to Coco.
> 
> Perhaps it should be in its own repository because it has its own lifecycle and users that are different from all of the other content.

Moved to its own new repository

**Comment by davidradl** [comment]
I have considered 2 patterns 

Pattern A : where we define a repository connector and event mapper in the repository pattern  there is an embedded native repository that all the type and find calls delegate down to. There are 2 metadata collections the outer one and the hidden inner one. I have this working in a prototype - hard coded to an embedded in memory repository

Pattern B : The idea is that we could reuse an existing native connector and associate it with an event mapper.  This is simpler as the event mapper is the only new piece. I define the in memory repository with local-repository/mode/in-memory-repository. In this case it is not a repository proxy (in terms of its mode). If I then try /local-repository/event-mapper-connection  it is rejected as we are not a repository proxy. I have changed this logic to accept a native repository. The event mapper is added but does not start. I have coded  a fix to allow the event mapper to be created and started, it is https://github.com/odpi/egeria/pull/6608. The issue I see now is that if I create a reference copy from the event mapper - I does not have a home metadata repository.  So with this pattern I need to create a new home repository collection id associated with the event mapper that is different from the native repositories (or saveEntityReference are rejected) and persist it in the config. Pattern B does not currently allow add calls to be issued to the 3rd party repository, unless the event mapper polls for changes in the native repository. In theory this pattern could be used with a repository proxy connector as well as a native repository connector. 

If we think that both patterns are valid then I can include samples of both in the change associated with this issue. 

Any thoughts @mandy-chessell @planetf1 @lpalashevski @cmgrote

**Comment by mandy-chessell** [comment]
I like pattern 2 but I think it is going to be necessary to have a wrapping repository connector (pattern 1) to ensure the metadata collection id is managed correctly.  However, this wrapping repository connector can be a standard implementation that will work for any third party repository where the event mapper completely controls the metadata that is made available to the cohort.  It would then be possible to add a helper method to the repository proxy admin commands to create the nested connection correctly in the admin services.

Before we do that ... this is the type of hack that would be needed to make pattern 2 work ...

* it is possible to use a native repository implementation as the repository proxy's local repository - however it is important that it configured as such and not configured using the metadata access store command such as `local-repository/mode/in-memory-repository`.  It needs to be configured using the repository proxy methods.
* the event mapper can get the home metadata collection id from the native repository connector using the standard getMetadataCollectionId method.  This needs to be the value that is set in the header of the reference copies because this is the identifier that the repository proxy registered with the rest of the cohort.
* It might be possible for the event mapper to update the metadata collection id in the in memory connector to a new one so that the save reference copies method works.  It would need to call setMetadataCollectionId() after it has initialized.  This seems a bit dodgy.  I would suggest that this additional metadata collection is retrieved from the confguration properties of the event mapper connection so it is possible to trace where the value came from if it appears in error messages.

**Comment by davidradl** [comment]
thanks Mandy. So you are suggesting something like :
![config polling connector drawio](https://user-images.githubusercontent.com/39792797/172181296-a1113395-2cd2-46bd-936d-33cc0b969c8e.png).

**Comment by davidradl** [comment]
And if we want to push the content to the 3rd party the event mapper would need to poll for changes and then issue the appropriate call to the 3rd party technology.

**Comment by mandy-chessell** [comment]
The picture above shows the structure of the configuration document for the repository proxy which is confusing.  Are you suggesting that the configuration document structure needs updating?  **No change is required to the configuration document structure for either pattern.**  The configuration is all within the local repository section of the configuration document.  There is a property for the *local repository local connection* and another property for the *event mapper connection*.  The type/presence/nesting of the repository connectors is controlled from the connection information set in these two variables in the standard way you would expect for the OCF.

For pattern 1
* The *local repository local connection* property is set to a VirtualConnection with the connection information about the wrapping connector in it and an embedded connection object for the native repository.  The outer virtual connection would have the inner's dummy metadata collection id in a configuration property so it can initialize the inner native repository connector when its proper home metadata collection id is set up.  As normal, when the ConnectorBroker is passed the virtual connection, it created connectors for all nested connections and these connectors are passed to the connector on the 'initializeEmbeddedConnectors' method.
* The *event mapper connection* is set to a connection object for the event mapper.  When it is initialized, it calls getMetadataCollectionId on the repository connector passed in the initialize method to get the proper home metadata collection id to use when it creates entities/relationships.  The repository connector is the wrapping connector.

For pattern 2
* The *local repository local connection* property is set to a Connection with the connection information about the native repository.  
* The *event mapper connection* is set to a connection object for the event mapper.  The dummy metadata collection id for the native repository is set as a configuration property in the event mapper's connection.  When the event mapper is initialized it is passed the native repository connector.  It calls the repository connector's getMetadataCollectionId to get the "proper" home metadata collection id to use in new elements and then calls setMetadataCollectionId to set up the dummy metadata colllection id so saving reference copies works.

**Comment by mandy-chessell** [comment]
> And if we want to push the content to the 3rd party the event mapper would need to poll for changes and then issue the appropriate call to the 3rd party technology.

I do not understand this comment above

- do you mean push content from the cohort to the third party metadata repository?  The event mapper is not involved in this use case of course since it is is only involved in events from the third party technology.  Events from the cohort are handled by OMRS and passed to the repository connector via the save reference copies methods.  If you want to save these in the third party repository, the repository connector needs to call the third party repository when these methods are called - you would need pattern 1 for that.

- alternatively do you mean that events created from the third party metadata repository's content by the event mapper should also be stored back in the third party's metadata repository - is that to save ids? Confused.

**Comment by davidradl** [comment]
Hi Mandy, no I was not thinking this required any config changes. I was just being explicit for my understanding.

I think we are saying the preferred option would be:
Pattern 3. which would be the same as pattern 1, but
-  driven from the configuration 
-  all the logic relating to polling and issuing of the OMRS calls being in the event mapper.  
 - new admin call(s) to allow the virtual connection to be configured

The  inner's dummy metadata collection id is the outer's metadata collection id- suffixed with '-embedded'. But we coudl pick this up from the configuration file I think, if there is one stored there.

I am thinking this would be best to work on pattern 3, rather than attempting to get pattern 2 working, when we know were aren't going to use it. 

on the comment `And if we want to push the content to the 3rd party the event mapper would need to poll for changes and then issue the appropriate call to the 3rd party technology.` . I mean your first bullet point. As far as I can can see, there would be 2 callers to saveEntityReferenceCopy: 
- as a result of an inbound OMRS event - where we would want to update the 3rd party technology and the embedded repository.  
- as a result of a polling call from the event mapper, where we would not want to update the 3rd party technology and only store it in the embedded repository.  
I am not sure if the code could tell the difference, unless it knew the outer metadata collection id and could check against that. I hope this makes sense.

**Comment by mandy-chessell** [comment]
The save reference copies are made against the outer repository which knows its home metadata collection id, so it knows when the element is from the home repository (ie via the event mapper) and so does not need to pass the element onto the third party repository.  With this feature, the wrapping repository is a specialized repository for the third party repository because it needs to know how to call its proprietory methods.

If the inner dummy metadata repository is derived from the real home metadata collection id then no need to add it to the connection object - in fact important that is is not added in case the home metadata collection id is updated.  I like it as a solution because useful for diagnostics

From 
> all the logic relating to polling and issuing of the OMRS calls being in the event mapper.

I assume you mean calls to the event processor and repository connector rather than more general OMRS calls?

**Comment by davidradl** [comment]
@mandy-chessell that makes sense. For the first stage I will work on having a generic outer repository that passes everything down to the inner repository. Maybe all it call the outer connector something like RepositoryProxyCachingConnector. I notice there is a local repository mode METADATA_CACHE. I assume we do not want to use this, as we want to be able to work with any repository proxy or native repository.    

On the all the logic relating to polling and issuing of the OMRS calls being in the event mapper. I was thinking of the <outer collection>.saveEntityReference calls and the like that are called in the polling loop. In my current prototype this logic is in the repository connector, so I need to move it.

**Comment by mandy-chessell** [comment]
One other point - the new repository proxy admin server method would only be for the case where the wrapping repository connector is our own implementation (ie RepositoryProxyCachingConnector/RepositoryProxyCachingProvider) and the native connection is supplied - the new admin method builds the virtual connection around the native connection.

For the case where the wrapping connector is specialized for the third party repository then the normal call to set the repository connection would be used because the caller has to provide both the outer virtual connection and the embedded native connection so no benefit provided beyond the current method

**Comment by davidradl** [comment]
@mandy-chessell fyi I have the configuration properties coming through on the repository connector.
